apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-app
spec:
  selector:
    matchLabels:
      app: java-app
  replicas: 1
  template:
    metadata:
      labels:
        app: java-app
    spec:
      containers:
        - name: java-app
          image: tabrezid54/java-login-app-sidecar:latest
          ports:
            - containerPort: 8080
          env:
            - name: MYSQL_DATABASE
              value : "UserDB"
            - name: MYSQL_USER
              value : "tab"
            - name: MYSQL_PASSWORD
              value : "Tab123"
        - image: tabrezid54/mysql
          name: mysql
          env:
            - name: MYSQL_ROOT_PASSWORD
              value : "password"
            - name: MYSQL_DATABASE
              value : "UserDB"
            - name: MYSQL_USER
              value : "tab"
          ports:
            - containerPort: 3306
              name: mysql

---

apiVersion: v1
kind: Service
metadata:
  name: java-app-svc
spec:
  type: NodePort
  selector:
    app: java-app
  ports:
    - protocol: "TCP"
      port: 8080
      nodePort: 30008
