apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-app
spec:
  selector:
    matchLabels:
      app: java-app
  replicas: 3
  template:
    metadata:
      labels:
        app: java-app
    spec:
      containers:
        - name: java-app
          image: tabrezid54/java-login-app:latest
          ports:
            - containerPort: 8080
          env:  
            - name: DB_HOST   
              value: "mysql"
            - name: DB_NAME  
              value : "UserDB"
            - name: DB_USERNAME  
              value : "tab"
            - name: DB_PASSWORD 
              value : "password"
