apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-app
spec:
  selector:
    matchLabels:
      app: java-app
  replicas: 1
  template:
    metadata:
      labels:
        app: java-app
    spec:
      containers:
        - name: java-app
          image: tabrezid54/java-login-app-sidecar:latest
          ports:
            - containerPort: 8080
          env:
            - name: MYSQL_DATABASE
              value : "UserDB"
            - name: MYSQL_USER
              value : "tab"
            - name: MYSQL_PASSWORD
              value : "Tab123"
        - image: tabrezid54/mysql
          name: mysql
          env:
            - name: MYSQL_ROOT_PASSWORD
              value : "password"
            - name: MYSQL_DATABASE
              value : "UserDB"
            - name: MYSQL_USER
              value : "tab"
          ports:
            - containerPort: 3306
              name: mysql
        - name: nginx
          image: nginx
          ports:
           - containerPort: 80
          volumeMounts:
              - name: nginx-conf
                mountPath: /etc/nginx/nginx.conf
                subPath: nginx.conf
                readOnly: true
      volumes:
      - name: nginx-conf
        configMap:
          name: nginx-conf
          items:
            - key: nginx.conf
              path: nginx.conf


---

apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  type: NodePort
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
    nodePort: 30010
  selector:
    app: nginx

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-conf
data:
  nginx.conf: |
    worker_processes 1;
    events { worker_connections 1024; }
    http {
        sendfile on;
        server {
            listen 80;
            location / {
                proxy_pass http://localhost:8080;
                proxy_redirect off;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Host $server_name;
            }
        }
    }

